### ISSUE TITLE
Time delay request 

### ISSUE THREAD

**Issue by CustomCasindo** [EasyG0ing1/SimpleEncoder#1]
Can you add delay time for your code? 

example:
if (encoder.idle) for 1 minute 
{digitalWrite (led, HiGH)}

Thanks

**Comment by EasyG0ing1** [comment]
@CustomCasindo 

The way to do something like that would be with a simple timer library like [BlockNot](https://github.com/EasyG0ing1/BlockNot) (another library I wrote) and the code would look like this:

```
#include <Arduino.h>
#include <SimpleEncoder.h>
#include <BlockNot.h>

const int BUTTON = 10;
const int PIN_A = 11;
const int PIN_B = 12;
const int LED = 9;

SimpleEncoder encoder(BUTTON,PIN_A,PIN_B);

BlockNot timer(60, SECONDS);

void setup() {
    Serial.begin(115200);
    pinMode(LED,OUTPUT);
}

void loop() {
    if(encoder.CLOCKWISE) {
        timer.RESET;
        digitalWrite(LED,LOW);
    }
    if(encoder.COUNTERCLOCKWISE) {
        timer.RESET;
        digitalWrite(LED,LOW);
    }
    if(timer.TRIGGERED) {
        digitalWrite(LED,HIGH);
    }
}
```

**Comment by CustomCasindo** [comment]
Amazing, iam very like this library, how about reverse? 
if (encoder, CHANGING) for 1 minute
{...} ?

Thanks

**Comment by EasyG0ing1** [comment]
@CustomCasindo That code covers both directions of the encoder. 

When you turn the encoder in either direction, it merely resets the timer, then when the encoder is idle the timer will trigger in 60 seconds and run whatever code you want to run at that point.

It would be almost impossible to have the encoder library do any "timeout" function without simply including BlockNot inside the rotary encoder library but even then there is no way to automate the triggering of any code at a given time period, you would still need to check in the loop to see if the timer had triggered because Arduinos are not multi-threaded processors and they don't execute code like a computer does so there's really no way to have code running in the background while your main sketch does other stuff.

The solution I gave you is the best way to accomplish what you're trying to do.

☺

**Comment by CustomCasindo** [comment]
Sorry, I mean in another separate program, not combined. 
How is it used? If the encoder rotates continuously for 1 minute, then the led is on. Can you provide an example of the code for using this library, because I'm still new and still learning.  Thanks

**Comment by EasyG0ing1** [comment]
@CustomCasindo - Yes I completely understand being new to this stuff and getting past the larger learning curve.

So let's assume that we're talking about a "standard" Arduino. This would mean that the Arduino would be using the typical ATMEL chip as its core CPU like the ATMega328 - whenever you're talking about an Arduino UNO or a NANO or any of those classes, the ATMega328 is the chip you're referring to and many of the Arduino chips use the same architecture model which makes using them very easy since the same code will run on all of them. 

Even the newer chips like the Raspberry Pi Pico, which uses an ARM processor which is nothing like the ATMega architecture,  can run the same code that will run on the Atmel chips so the entire Arduino ecosystem then becomes VERY ATTRACTIVE because there is a wide range of chips that can be used without ever needing to worry about learning different programming code for each chip.

The advantage, however, of using a chip like the one in the Pi Pico is that these newer chips offer insanely fast clocks as well as multiple cores which then allows you to run different code simultaneously in a different core of the processor. I've done it with an application that has to simultaneously step two different stepper motors in a time-synchronized manner and the results were excellent.

OK - all that being said ... I wanna say next what you probably already know, but ill say it anyway to drive the point home...

When using C++ to write your Arduino sketches, the model for the sketch is always the same no matter what...

* Import your libraries
* Declare your variables and class instances (which come from your imports)
* Write your methods (some people call them functions)
* Write your setup() and your loop()

Libraries are almost always the best way to use hardware that you connect to the Arduino and the more complicated that hardware is, the more valuable a library is that was written for that hardware because it saves you the painful process of having to learn how to make that hardware do what it does.

For example, using a DRV8825 stepper motor driver can be done directly fairly easily but there are libraries out there that make it really easy to use and also add some features that can be handy in certain scenarios. But where libraries are even more valuable is when the hardware that you're connecting uses something like I2C to communicate where that code requires an understanding of how to use I2C in the first place but also in how to send the right commands to the device which are always in hexadecimal and can only be understood after reading the datasheet for the device. So then a library allows you to just use the device without ever needing to study it and learn how it works under the hood.

Then there are other libraries that have nothing to do with hardware and are just nicely packaged classes that you import into your sketch that give you functionality with the Arduino itself that you don't have to write from scratch.

This is what my BlockNot timer library is as matter of fact. It has no connection whatsoever to any kind of hardware. In fact, what it does, is it relies on the built-in Arduino method called `milllis()` and another one called `micros()` and the millis method merely gives you the number of milliseconds that have passed since the Arduino was powered up and the micros method does the same thing only it gives you microseconds.

An ATMegsa328 microprocessor is considered a low-end and even a slow chip by today's standards. HOWEVER, just to give you an idea of how fast it is (even though its FAST is still slow by today's standards), the loop() method in a sketch on an ATMega328 processor will execute as many as one MILLION times per second.

THATS A LOT ...

Most beginners rely on the `delay()` method for timing events, but the problem with delay is that it is a BLOCKING method which means that while delay is running, your program stops running until delay is done. In fact the delay method stops the microcontroller from doing anything else at all while the delay is running ... not even interrupts will work wile a delay is executing. Many people believe that delay should not even be a command available to use because it seizes complete control of the microcontroller.

So let's say you have a loop that looks like this:
```
loop() {
    checkMoistureReading();
    digitalWrite(LED,HIGH);
    delay(500);
    digitalWrite(LED,LOW);
    delay(500);
}
```
In that loop, there is a full 1 second where your code never checks the moisture reading (from whatever device is providing that) and in fact, the code only checks the moisture reading one time every second (because we have two delays, each at 500 milliseconds) instead of checking it almost a million times every second ... which for something like a moisture reading might be just fine ... but think about a situation where you need to step a stepper motor and so you have to send highs and lows to a stepper motor driver hundreds of times in a millisecond while at the same time, blink your led off and on every second. This is where using what is called NON BLOCKING TIMERS come into play because a non-blocking timer never stops the execution of your loop it merely checks to see if the desired time has passed with each run of the loop and if that time has passed only then does it do something. So when you use a library like BlockNot, you can still get the LED to blink on and off every second, but the timer literally only consumes a single clock cycle of the CPU whereas using the delay() command will consume MILLIONS of clock cycles of the CPU and it will BLOCK your code from running at all while the delay method is waiting for the time to pass that you specified.

NON-blocking timers aren't really "timers" per se', they simply record the value of the `millis()` method - usually into a long type variable named startTime, then as time passes it checks `millis()` again and subtracts that larger number from startTime to see if the desired time has elapsed. and while we're waiting for that elapsed period of time, the rest of your code continues to execute in your loop.

Here is what a non-blocking timer looks like when you write it manually:
```
long startTime = millis();
long timerDuration = 2300;


loop() {
    long endTime = millis();
    if ((endTime - startTime) >= timerDuration) {
        //Code that runs every 2300 miliseconds
    }
}
```

BlockNot simply records the millis() at the moment you instantiate the library then it checks millis() against that recorded start time each time you ask it if the timer has "TRIGGERED" ...

This is how you do the same non-blocking timer using BlockNot:

```
BlockNot myTimer(2300);

loop() {
    if(myTimer.TRIGGERED) {
        //Code that runs every 2300 milliseconds
    }
}
```
Notice how much simpler it is and how much easier it is to write the code and most importantly, how much easier it is to READ the code and actually make sense of what it's doing.

Both versions of a non-blocking timer in those examples would create a timer that triggers every 2300 milliseconds, (or 2.3 seconds). The BlockNot library merely stores the value returned from the millis() method into a variable. Then when your code checks to see if it triggered, it looks at the millis() value and subtracts it from the millis() value when the timer was created and if the time that has passed is equal to or greater than the defined time in the timer (2300 ms) it responds with TRUE indicating that it triggered. It also then records the current millis() as the new start time for the timer so that it can re-trigger in another 2300 ms.

And without ever once stopping the rest of your sketch from running.

When it comes to the rotary encoder, the library `SimpleEncoder` only does one thing... it checks to see if the encoder is being rotated either clockwise or counterclockwise and returns TRUE if it is in fact being rotated. 

Because that is all that the library does, if I then tried to insert a timer into a method that is supposed to check to see if the rotary is moving, would add more code to those methods which might result in the code not working fast enough to give you an accurate response to the question of "Is the rotary being turned"? And that would almost always turn out to provide you with inaccurate information because determining whether a rotary in an encoder is turning or not, requires the ability to check the value of certain pins which needs to be done at very high speeds. So a timer in that mix would just end up making the library useless even in normal light-duty applications.

Because of that, you need to manage the 60-second requirement on the encoder (at which point you would then turn on an LED as you suggested) OUTSIDE of the encoder library. This will give you the most accurate implementation of the function you are stating that you need.

So, because BlockNot is just a nicely packaged class that provides many easy-to-use features, we simply leverage the `RESET` feature of the timer after asking the SimpleEncoder library to tell us if the encoder is being turned (clockwise OR counter-clockwise), and if it is being turned, then we RESET the timers startTime to be that moment in time. Then, timer is reset and will not TRIGGER for another 60 seconds so that if the encoder is not moved at all in 60 seconds, we can implement code once the timer triggers and thus successfully achieve the result of turning on an LED if the encoder has not moved in the previous 60 seconds.

I hope at least some of that made sense...

**Comment by EasyG0ing1** [comment]
Added the [Timeout](https://github.com/EasyG0ing1/SimpleEncoder/blob/master/examples/Timeout/Timeout.ino) example sketch into the library as well as a [Wiki article](https://github.com/EasyG0ing1/SimpleEncoder/wiki/Usage-Scenarios#usage-scenarios) on the topic.
