### ISSUE TITLE
Question: Why not INPUT_PULLUP pins for encoder?

### ISSUE THREAD

**Issue by MatthewSteeves** [EasyG0ing1/SimpleEncoder#3]
I noticed that your code sets the 2 encoder input pins to type INPUT instead of INPUT_PULLUP. That requires a little more complicated phyiscal layout with a 5V voltage source and additional resistors. From my vantage point, wouldn't it be simpler just to make them of the INPUT_PULLUP type, so that the micro provides the 5v to charge the caps, and also provides the resistor when the encoder pins are connected to ground? Then you would just need one external resistor per pin to slow the cap discharge rate. Wondering what drove your decision to "outsource" the 5V?
Thanks!
Matt

**Comment by EasyG0ing1** [comment]
@MatthewSteeves What drove my decision to source +5 as per the schematic was that this is the recommended setup for this type of encoder. Also, when you purchase these encoders attached to a PCB, this is the way they will be laid out on the PCB where you source +5 through the two voltage dividers and your RC circuit has a consistent timing. You could, of course wire it up as you suggest and change the pins to be INPUT_PULLUP and in theory it should work fine provided that the timing of the RC circuit is the same. Though I don't see the timing being too critical in this application since it's only looking for change and not change over time ... though if the charge time of the cap were too slow, you could potentially miss marks when reading the values to determine direction. But I think your cap would have to be significantly LARGER in order to see that kind of exaggeration.

**Comment by MatthewSteeves** [comment]
Circling back to this as I'm re-visiting the encoder debounce circuit. I see the potential flaws in my idea (namely, the potential for charge time to be too slow). So for fun, I [simulated the circuit](https://falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWEAmaYAcBmMkFgCwYBsyk6+RIR6ISCktApgLRhgBQA5uAOyWGUwfEPnw0GkdgCcQATkrJk+OQvTiU8SQGcQmUijUp8DZIeUQAZgEMANlsYgAogDsAxgHsAJoykAdLVoA7gCWAC6uABbsrryUmAjIsSJg-OAsPFCwkBAwcDnSSfGJQqrqOPDsAEoqKEo1KRJQIgxIjTAIXLr6pjR6DJjUTZKBNT1JY8PjhkomhpPyBr2JY8jsAB4gzMgKRJTC27Ii4JQAau42oVacjP5Wof4ACgCSAHLs7rog6ms45Zi0mXgYFkCGwyFaKE+mHYmBoEAAYjkNPBaJpNhAHgBXGw2ACqAAcAPqVRhaYJaULuKTsIA) on falstad.com. From reading, it seems that the actual value of the internal pullup resistors may vary between 20k to 50k, I made the corresponding resistor in the sim adjustable via a slider. It's neat to observe the behaviour of the voltage vs time graph at the bottom. 

Based on the results and a discussion with Claude.AI, there SHOULD be enough charge time in between switching "events" to use the 5V from the chip's rail. (Claude estimates charge time under 20ms should be ok). However, there's a lot of assumptions, and the proofs always in the pudding. I think I'll try it just to see.

**Comment by EasyG0ing1** [comment]
@MatthewSteeves - Did you get a chance to work it ujp[ on a breadboard yet? Looking at the simulation you made, it's too bad they don't have an object that can model the rapid closing and opening of a switch like these rotary knobs  do ... it would be interesting to set something like a rotation speed of the knob which would then properly simulate the closing and opening of the switch to see what happens in the graph. With that kind of data, you could tighten up the debounce code nicely ... but then again ... using a scope is the best way to go about it I suppose ;-)

**Comment by MatthewSteeves** [comment]
@EasyG0ing1 Hey yup I did and it's working beatifully! Project's on pause at the moment, but when I get back to it I'll upload a screenshot of the scope data. Of course, I'm sure it's not the right solution for all situations, but for the relatively slow spinning I'm using the encoder for (changing values for a menu), it's able to respond fast enough.

**Comment by EasyG0ing1** [comment]
@MatthewSteeves Looking forward to it.
